### ISSUE TITLE
初始化失败

### ISSUE THREAD

**Issue by daobage** [yale8848/CacheWebView#93]
Process: com.example.php.webviewdemo, PID: 26774
    java.lang.NoClassDefFoundError: Failed resolution of: Lokhttp3/Cache;
        at ren.yale.android.cachewebviewlib.WebViewCacheInterceptor.initHttpClient(WebViewCacheInterceptor.java:90)
        at ren.yale.android.cachewebviewlib.WebViewCacheInterceptor.<init>(WebViewCacheInterceptor.java:76)
        at ren.yale.android.cachewebviewlib.WebViewCacheInterceptor$Builder.build(WebViewCacheInterceptor.java:369)
        at ren.yale.android.cachewebviewlib.WebViewCacheInterceptorInst.init(WebViewCacheInterceptorInst.java:25)
        at com.example.php.webviewdemo.App.onCreate(App.kt:10)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1028)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5662)
        at android.app.ActivityThread.-wrap2(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1706)
        at android.os.Handler.dispatchMessage(Handler.java:102)

**Comment by yale8848** [comment]
添加混淆配置试试：
```
#CacheWebview
-dontwarn ren.yale.android.cachewebviewlib.**
-keep class ren.yale.android.cachewebviewlib.**{*;}

#okhttp
-dontwarn okhttp3.**
-keep class okhttp3.**{*;}

#okio
-dontwarn okio.**
-keep class okio.**{*;}
```

**Comment by yale8848** [comment]
是不是okhttp包冲突了，我库里也用到okhttp了，如果是这个问题，可以在用exclude试试

**Comment by liuhuiAndroid** [comment]
我的天，这个依赖不加竟然无法初始化
添加okhttp的依赖
implementation 'com.squareup.okhttp3:okhttp:3.10.0'
